name: positron
version: '0.1.0.0'
synopsis: Experiment
description: Please see README.md
category: Database
author: XT
maintainer: e@xtendo.org
copyright: 2016 XT
license: Apache-2.0
github: xtendo-org/positron

default-extensions:
- LambdaCase
- OverloadedStrings
- RecordWildCards
- TemplateHaskell

library:
  source-dirs: library
  exposed-modules:
  - Positron
  - Positron.UUID
  dependencies:
  - attoparsec
  - bytestring
  - postgresql-libpq
  - scientific
  - template-haskell
  - text
  - base >=4.7 && <5

tests:
  positron-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - positron
